"""new fields in User table

Revision ID: 915e10d28bc4
Revises: 88ff1ee372f0
Create Date: 2018-12-14 13:26:29.659862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915e10d28bc4'
down_revision = '88ff1ee372f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
